use `springboot`;

INSERT INTO `springboot`.`user` (`avatar`, `email`, `full_name`, `password`, `username`) VALUES ('https://i.ibb.co/GMbLW63/LOGO.png', 'admin@gmail.com', 'Phạm Xuân Toán', '1234', 'admin');
INSERT INTO `springboot`.`user` (`avatar`, `email`, `full_name`, `password`, `username`) VALUES ('https://i.ibb.co/GMbLW63/LOGO.png', 'xuantoan@gmail.com', 'Phạm Xuân Toán', '1234', 'xuantoan');
INSERT INTO `springboot`.`user` (`avatar`, `email`, `full_name`, `password`, `username`) VALUES ('https://i.ibb.co/bJ8LBz4/avatar-06.jpg', 'thanhtri@gmail.com', 'Trần Thanh Trí', '1234', 'thanhtri');
INSERT INTO `springboot`.`user` (`avatar`, `email`, `full_name`, `password`, `username`) VALUES ('https://i.ibb.co/bJ8LBz4/avatar-06.jpg', 'quocviet@gmail.com', 'Nguyễn Quốc Việt', '1234', 'quocviet');

INSERT INTO `springboot`.`category` (`category_name`) VALUES ('IPhone');
INSERT INTO `springboot`.`category` (`category_name`) VALUES ('SamSung');
INSERT INTO `springboot`.`category` (`category_name`) VALUES ('Xiaomi');
INSERT INTO `springboot`.`category` (`category_name`) VALUES ('Oppo');

INSERT INTO `springboot`.`product` (`description`, `price`, `product_image`, `product_name`, `quantity`, `rate`, `category_id`) VALUES ('Apple đã chính thức trình làng bộ 3 siêu phẩm iPhone 11, trong đó phiên bản iPhone 11 64GB có mức giá rẻ nhất nhưng vẫn được nâng cấp mạnh mẽ như iPhone Xr ra mắt trước đó.', '11.999.000', 'https://i.ibb.co/zFYY04w/iphone-11-trang-200x200.jpg', 'Điện thoại iPhone 11', '100', '5', '1');
INSERT INTO `springboot`.`product` (`description`, `price`, `product_image`, `product_name`, `quantity`, `rate`, `category_id`) VALUES ('Galaxy S22 Ultra 5G chiếc smartphone cao cấp nhất trong bộ 3 Galaxy S22 series mà Samsung đã cho ra mắt. Tích hợp bút S Pen hoàn hảo trong thân máy, trang bị vi xử lý mạnh mẽ cho các tác vụ sử dụng vô cùng mượt mà và nổi bật hơn với cụm camera không viền độc đáo mang đậm dấu ấn riêng.', '25.990', 'https://i.ibb.co/121HB96/samsung-galaxy-s22-ultra-xanh-reu-1-1.jpg', 'Điện thoại Samsung Galaxy S22 Ultra 5G 128GB', '100', '4', '2');
INSERT INTO `springboot`.`product` (`description`, `price`, `product_image`, `product_name`, `quantity`, `rate`, `category_id`) VALUES ('Samsung Galaxy S22+ 5G 128GB được Samsung cho ra mắt với với ngoại hình không có quá nhiều thay đổi nhưng được nâng cấp đáng kể về thông số cấu hình bên trong và thời gian sử dụng, chắc hẳn sẽ mang lại những trải nghiệm thú vị dành cho bạn.', '21.990', 'https://i.ibb.co/fvFj7Br/374026974.jpg', 'Điện thoại Samsung Galaxy S22+ 5G', '100', '5', '2');
INSERT INTO `springboot`.`product` (`description`, `price`, `product_image`, `product_name`, `quantity`, `rate`, `category_id`) VALUES ('Sau bao khoảng thời gian dài chờ đợi thì vào ngày 08/09 chiếc điện thoại iPhone 14 cũng đã chính thức được lộ diện, với hàng loạt thông số kỹ thuật ấn tượng từ camera cho đến hiệu năng cực khủng. Từ ngày 14/10/2022 tại Thế Giới Di Động cũng đã chính thức mở bán tất cả các phiên bản iPhone 14 series để người dùng có thể sớm ngày được trải nghiệm.', '23.490', 'https://i.ibb.co/YLKs0xv/iphone-14-pro-tim-thumb-600x600.jpg', 'Điện thoại iPhone 14', '50', '5', '1');
INSERT INTO `springboot`.`product` (`description`, `price`, `product_image`, `product_name`, `quantity`, `rate`, `category_id`) VALUES ('Điện thoại Redmi được mệnh danh là dòng sản phẩm quốc dân ngon - bổ  - rẻ của Xiaomi và Redmi Note 11 (4GB/64GB) cũng không phải ngoại lệ, máy sở hữu một hiệu năng ổn định, màn hình 90 Hz mượt mà, cụm camera AI đến 50 MP cùng một mức giá vô cùng tốt.', '4.390', 'https://i.ibb.co/qmpj5vB/xiaomi-redmi-note-11-1-2.jpg', 'Điện thoại Xiaomi Redmi Note 11', '100', '5', '3');
INSERT INTO `springboot`.`product` (`description`, `price`, `product_image`, `product_name`, `quantity`, `rate`, `category_id`) VALUES ('Cuối cùng Xiaomi 12T Pro cũng đã chính thức lộ diện trên thị trường sau hàng loạt thông tin rò rỉ về thông số, đúng như dự đoán thì độ phân giải trên camera của phiên bản này được nhà sản xuất nâng cấp lên đến 200 MP, giúp máy trở thành thiết bị có khả năng ghi hình sắc nét thuộc top đầu giới smartphone, đi kèm với đó là màn hình chất lượng cùng bộ vi xử lý mạnh mẽ xứng tầm flagship.', '16.990', 'https://i.ibb.co/hdXbSQ6/xiaomi-12t-pro-den-1.jpg', 'Điện thoại Xiaomi 12T Pro', '70', '5', '3');
INSERT INTO `springboot`.`product` (`description`, `price`, `product_image`, `product_name`, `quantity`, `rate`, `category_id`) VALUES ('Reno6 Z 5G đến từ nhà OPPO với hàng loạt sự nâng cấp và cải tiến không chỉ ngoại hình bên ngoài mà còn sức mạnh bên trong. Đặc biệt, chiếc điện thoại được hãng đánh giá “chuyên gia chân dung bắt trọn mọi cảm xúc chân thật nhất”, đây chắc chắn sẽ là một “siêu phẩm\" mà bạn không thể bỏ qua.', '7.490', 'https://i.ibb.co/SR72B8K/oppo-reno6-z-5g-den-1-org.jpg', 'Điện thoại OPPO Reno6', '50', '3', '4');
INSERT INTO `springboot`.`product` (`description`, `price`, `product_image`, `product_name`, `quantity`, `rate`, `category_id`) VALUES ('OPPO Reno8 Pro 5G ra mắt với sự đột phá về phần camera khi đây là thiết bị đầu tiên thuộc dòng Reno được tích hợp NPU MariSilicon X, được xem là NPU cao cấp nhất đến từ OPPO (2022) có khả năng xử lý hình ảnh đỉnh cao. Kèm với đó là một con chip mạnh mẽ đến từ nhà MediaTek giúp bạn có thể cân được mọi tựa game đang hiện hành.', '18.990', 'https://i.ibb.co/TgdRqWf/oppo-reno8-pro-black-1.jpg', 'Điện thoại OPPO Reno8', '60', '4', '4');

INSERT INTO `springboot`.`comment` (`content`, `product_id`, `user_id`) VALUES ('Điện thoại đẹp!', '1', '2');
INSERT INTO `springboot`.`comment` (`content`, `product_id`, `user_id`) VALUES ('Điện thoại xịn!', '1', '3');
INSERT INTO `springboot`.`comment` (`content`, `product_id`, `user_id`) VALUES ('Dùng rất thích!', '1', '4');

INSERT INTO `springboot`.`comment` (`content`, `product_id`, `user_id`) VALUES ('Điện thoại đẹp!', '2', '2');
INSERT INTO `springboot`.`comment` (`content`, `product_id`, `user_id`) VALUES ('Điện thoại xịn!', '3', '2');
